export const BlogData = [
    
    {
        id : 1,
        title : "html",
        body : "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Saepe nemo recusandae ab rem architecto dolorem quisquam atque, fugit quos voluptatem veniam molestiae totam earum hic voluptate blanditiis mollitia aspernatur ipsa nam magni sunt pariatur dolore voluptates assumenda. Placeat deserunt quae consectetur animi at. Saepe repudiandae assumenda cumque dolorum soluta sapiente distinctio natus possimus rerum necessitatibus obcaecati in velit non aliquid animi cupiditate incidunt voluptatibus, deserunt dicta ex? Saepe dicta aut rem ea fuga hic iusto sequi quo quaerat architecto expedita, repellendus, aperiam harum natus dolorum ipsum, eum provident? Deserunt aspernatur temporibus architecto optio ducimus? Suscipit similique expedita velit est at, labore facere hic repudiandae architecto dolores dolore quas aliquam sunt blanditiis aperiam deserunt eaque omnis, adipisci beatae natus possimus veniam quod tempora assumenda? Voluptatum cumque animi ducimus, quibusdam, at tempore quidem velit molestiae voluptates qui, impedit inventore. Eum quod minus nisi enim inventore magni nostrum commodi totam, doloribus sequi voluptatem quibusdam, hic quidem impedit ea eligendi similique deserunt, fugiat nesciunt. Perspiciatis blanditiis voluptates aliquid consequuntur quae asperiores deserunt dolores reiciendis atque veniam iure, ipsam illo tempore et dignissimos ex, alias corrupti sit distinctio."
    },

    {
        id : 2,
        title : "css",
        body : "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Saepe nemo recusandae ab rem architecto dolorem quisquam atque, fugit quos voluptatem veniam molestiae totam earum hic voluptate blanditiis mollitia aspernatur ipsa nam magni sunt pariatur dolore voluptates assumenda. Placeat deserunt quae consectetur animi at. Saepe repudiandae assumenda cumque dolorum soluta sapiente distinctio natus possimus rerum necessitatibus obcaecati in velit non aliquid animi cupiditate incidunt voluptatibus, deserunt dicta ex? Saepe dicta aut rem ea fuga hic iusto sequi quo quaerat architecto expedita, repellendus, aperiam harum natus dolorum ipsum, eum provident? Deserunt aspernatur temporibus architecto optio ducimus? Suscipit similique expedita velit est at, labore facere hic repudiandae architecto dolores dolore quas aliquam sunt blanditiis aperiam deserunt eaque omnis, adipisci beatae natus possimus veniam quod tempora assumenda? Voluptatum cumque animi ducimus, quibusdam, at tempore quidem velit molestiae voluptates qui, impedit inventore. Eum quod minus nisi enim inventore magni nostrum commodi totam, doloribus sequi voluptatem quibusdam, hic quidem impedit ea eligendi similique deserunt, fugiat nesciunt. Perspiciatis blanditiis voluptates aliquid consequuntur quae asperiores deserunt dolores reiciendis atque veniam iure, ipsam illo tempore et dignissimos ex, alias corrupti sit distinctio."
    },

    {
        id : 3,
        title : "js",
        body : "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Saepe nemo recusandae ab rem architecto dolorem quisquam atque, fugit quos voluptatem veniam molestiae totam earum hic voluptate blanditiis mollitia aspernatur ipsa nam magni sunt pariatur dolore voluptates assumenda. Placeat deserunt quae consectetur animi at. Saepe repudiandae assumenda cumque dolorum soluta sapiente distinctio natus possimus rerum necessitatibus obcaecati in velit non aliquid animi cupiditate incidunt voluptatibus, deserunt dicta ex? Saepe dicta aut rem ea fuga hic iusto sequi quo quaerat architecto expedita, repellendus, aperiam harum natus dolorum ipsum, eum provident? Deserunt aspernatur temporibus architecto optio ducimus? Suscipit similique expedita velit est at, labore facere hic repudiandae architecto dolores dolore quas aliquam sunt blanditiis aperiam deserunt eaque omnis, adipisci beatae natus possimus veniam quod tempora assumenda? Voluptatum cumque animi ducimus, quibusdam, at tempore quidem velit molestiae voluptates qui, impedit inventore. Eum quod minus nisi enim inventore magni nostrum commodi totam, doloribus sequi voluptatem quibusdam, hic quidem impedit ea eligendi similique deserunt, fugiat nesciunt. Perspiciatis blanditiis voluptates aliquid consequuntur quae asperiores deserunt dolores reiciendis atque veniam iure, ipsam illo tempore et dignissimos ex, alias corrupti sit distinctio. Facere debitis dolor veritatis quidem reiciendis facilis fuga eligendi, dignissimos molestiae quaerat! Voluptatem, itaque fugiat! Sit, unde nesciunt? Nam earum totam cumque perferendis natus, soluta quod quo quaerat exercitationem possimus fugit omnis doloribus cupiditate dolores, dolorum animi expedita suscipit. Ipsa sint sapiente reiciendis ipsum corrupti ratione, quisquam ab, quo quaerat enim est? Explicabo magni architecto fuga officia fugiat amet hic distinctio velit excepturi voluptatum! Velit enim laudantium, saepe perferendis beatae neque."
    },

    {
        id : 4,
        title : "php",
        body : "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Saepe nemo recusandae ab rem architecto dolorem quisquam atque, fugit quos voluptatem veniam molestiae totam earum hic voluptate blanditiis mollitia aspernatur ipsa nam magni sunt pariatur dolore voluptates assumenda. Placeat deserunt quae consectetur animi at. Saepe repudiandae assumenda cumque dolorum soluta sapiente distinctio natus possimus rerum necessitatibus obcaecati in velit non aliquid animi cupiditate incidunt voluptatibus, deserunt dicta ex? Saepe dicta aut rem ea fuga hic iusto sequi quo quaerat architecto expedita, repellendus, aperiam harum natus dolorum ipsum, eum provident? Deserunt aspernatur temporibus architecto optio ducimus? Suscipit ore nemo culpa quasi. Reprehenderit voluptate at voluptatem iusto inventore illo laborum ratione sit quia rerum esse, error in eveniet, pariatur rem asperiores eaque deserunt. Fugit blanditiis nostrum molestias quas incidunt sapiente delectus cumque ea hic fuga, soluta magnam quae sed, impedit asperiores sit error quos necessitatibus voluptates! Quasi provident veritatis, placeat eos quidem esse mollitia perferendis nobis molestias eligendi nesciunt, maxime assumenda ex id! Laborum eius blanditiis, nesciunt consectetur mollitia similique tenetur hic aut numquam sunt voluptates aperiam harum exercitationem fuga aliquam ullam quidem, vel laboriosam quas excepturi ad reprehenderit repellendus voluptatum. Pariatur incidunt ullam quas nostrum aliquid. "
    },

    {
        id : 5,
        title : "react",
        body : "At corrupti minus vitae consequuntur ipsa, hic explicabo quos cum laboriosam voluptates! Laboriosam optio ea beatae, unde vitae asperiores iusto facere esse aut maxime porro dolore quasi. Modi perspiciatis non delectus fuga repellendus, et voluptates recusandae explicabo pariatur numquam quod corporis magni eum voluptas labore perferendis laudantium architecto ad commodi eius nihil saepe. Reiciendis enim distinctio atque quibusdam! Qui facilis amet corrupti perferendis sequi dicta odit omnis laboriosam, voluptates accusamus! Ratione consequuntur cumque fugit dignissimos doloremque excepturi reprehenderit nesciunt soluta nulla veniam non blanditiis laborum, distinctio labore, ullam eveniet? Adipisci animi alias consequatur voluptatum tempore reiciendis officiis magnam, ipsam consequuntur. Nihil cumque quis, pariatur distinctio maxime quo fuga, corrupti sint doloribus vel harum impedit quasi aliquam omnis deserunt eum? Rem maxime eveniet eius perferendis in est illum labore expedita, ratione nam, mollitia culpa quasi praesentium!  quaerat provident repellat numquam commodi repellendus tenetur, corporis cupiditate et vero aliquid dolores temporibus minus quibusdam laudantium porro magni doloribus explicabo qui repudiandae corrupti iste? Cupiditate dignissimos recusandae doloremque, non animi labore neque laudantium quaerat voluptatum, iusto necessitatibus distinctio fugit ducimus maxime voluptas laborum eum. "
    }
]